version: '3.9'
services:
  wisdomia-monolithic:
    container_name: wisdomia-monolithic-postgres-container
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Remmaped from 5432:5432 to 5435:5432
    volumes:
      - ./docker-volumes/postgres-wisdomia-monolithic-volume:/var/lib/postgresql/data
    networks:
      - backend


  redis:
    container_name: wisdomia-monolithic-redis-container # this is used for accessing the redis service <IMPORTANT>
    image: redis:alpine
    ports:
      - 6379:6379 
    command: redis-server --loglevel warning # TODO: Why, what and do we need log level?
    volumes:
      - ./docker-volumes/cache:/data


volumes:
  # sudo ls /var/lib/docker/volumes - should be here on local linux system
  esdata:

networks:
  backend:
    name: backend
